version: '2'

services:
  cassandra1:
    container_name: cassandra1
    image: cassandra:latest
    volumes:
      - /home/will/data/uni/year4/sem2/infs3208/a2/db/data/node1:/var/lib/cassandra/data
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=infs3208
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=d1
  cassandra2:
    container_name: cassandra2
    image: cassandra:latest
    volumes:
      - /home/will/data/uni/year4/sem2/infs3208/a2/db/data/node2:/var/lib/cassandra/data
    ports:
      - 9043:9043
    command: bash -c 'sleep 60; /docker-entrypoint.sh cassandra -f'
    depends_on:
      - cassandra1
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=infs3208
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=d1
      - CASSANDRA_SEEDS=cassandra1